codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: 0..100
  status:
    project:
      default:
        target: 90
        threshold: 1
        base: auto
        if_not_found: error
    patch:
      default:
        target: 90
        threshold: 1
        base: auto
        if_not_found: error

comment:
  layout: "reach, diff"
  behavior: default